<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Customers table — Customer Management module.
 *
 * Replaces the incompatible Sprint 0 migration (2026_06_25_000001).
 * Aligns with the approved Customer entity specification in:
 *   docs/database/entities.md
 *   docs/workflows/customer-workflow.md
 *   docs/architecture/decisions.md (Customer Management section)
 *
 * Customer lifecycle: prospect (default) → active → suspended → terminated
 * Customer number format: CUST-000001 (generated by CustomerService, not DB)
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('customers', function (Blueprint $table) {
            // ----------------------------------------------------------------
            // Identity
            // ----------------------------------------------------------------
            $table->id();

            $table->string('customer_number', 20)->unique()
                ->comment('Human-readable external identifier. Format: CUST-000001. Generated by CustomerService. Immutable after creation.');

            $table->string('name')
                ->comment('Full name (individual) or company name (business).');

            $table->enum('customer_type', ['individual', 'business'])->default('individual')
                ->comment('Passive field in v1.0. No differential business rules applied. See: Customer Type Classification for v1.0 decision.');

            // ----------------------------------------------------------------
            // Contact channels
            // ----------------------------------------------------------------
            $table->string('email')->nullable()->index();
            $table->string('phone', 30)->nullable()->index();
            $table->string('whatsapp_phone', 30)->nullable();
            $table->string('alt_phone', 30)->nullable();

            // ----------------------------------------------------------------
            // Service location
            // ----------------------------------------------------------------
            $table->text('address')->nullable()
                ->comment('Service installation address. Single address model for v1.0. See: Customer Contact Data Model decision.');
            $table->decimal('latitude', 10, 7)->nullable();
            $table->decimal('longitude', 11, 7)->nullable();

            // ----------------------------------------------------------------
            // Operational
            // ----------------------------------------------------------------
            $table->text('notes')->nullable()
                ->comment('Internal operational notes. Not customer-visible.');

            // ----------------------------------------------------------------
            // Foreign keys
            // ----------------------------------------------------------------
            $table->foreignId('cluster_id')->nullable()
                ->constrained('clusters')->nullOnDelete()
                ->comment('Nullable pre-seeded: becomes required when Cluster/ServiceArea modules are implemented.');

            $table->foreignId('service_area_id')->nullable()
                ->constrained('service_areas')->nullOnDelete()
                ->comment('Nullable pre-seeded: becomes required when Cluster/ServiceArea modules are implemented.');

            $table->foreignId('user_id')->nullable()
                ->constrained('users')->nullOnDelete()
                ->comment('Optional portal User account. SET NULL on User deletion.');

            // ----------------------------------------------------------------
            // Lifecycle
            // ----------------------------------------------------------------
            $table->enum('status', ['prospect', 'active', 'suspended', 'terminated'])
                ->default('prospect')
                ->index()
                ->comment('Customer account status. prospect = default/initial. See: CustomerStatus enum and customer-workflow.md.');

            // ----------------------------------------------------------------
            // Timestamps & soft delete
            // ----------------------------------------------------------------
            $table->timestamps();
            $table->softDeletes();

            // ----------------------------------------------------------------
            // Indexes
            // ----------------------------------------------------------------
            $table->index('customer_type');
            $table->index(['status', 'service_area_id']);
            $table->index('name');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('customers');
    }
};
