<?php

namespace App\Http\Requests\Auth;

use App\Enums\RoleStatus;
use Illuminate\Auth\Events\Lockout;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/**
 * LoginRequest — Identity & Access module.
 *
 * Enforces the full authentication flow in order:
 *   1. Rate limiting
 *   2. Credential validation (email + password)
 *   3. User status — only UserStatus::Active may authenticate
 *   4. Role assignment — at least one role must be assigned
 *   5. Role status — at least one assigned role must be Active
 *
 * All rejection paths use the same generic error message (trans('auth.failed'))
 * to prevent account status enumeration. Specific reasons are logged server-side.
 */
class LoginRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'email'    => ['required', 'string', 'email'],
            'password' => ['required', 'string'],
        ];
    }

    /**
     * Attempt to authenticate the request's credentials.
     *
     * Enforces status and role checks after credential validation.
     * On any failure, the session is invalidated and a generic error is returned
     * so that the failure reason is never revealed to the client.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function authenticate(): void
    {
        $this->ensureIsNotRateLimited();

        // ------------------------------------------------------------------
        // Step 1-2: Validate credentials and verify the user exists.
        // Auth::attempt() returns false for unknown email or wrong password.
        // ------------------------------------------------------------------
        if (! Auth::attempt($this->only('email', 'password'), $this->boolean('remember'))) {
            RateLimiter::hit($this->throttleKey());

            Log::warning('Login failed: invalid credentials.', [
                'email' => $this->string('email'),
                'ip'    => $this->ip(),
            ]);

            throw ValidationException::withMessages([
                'email' => trans('auth.failed'),
            ]);
        }

        /** @var \App\Models\User $user */
        $user = Auth::user();

        // ------------------------------------------------------------------
        // Step 3: Verify account status.
        // Only UserStatus::Active accounts may authenticate.
        // Inactive (decommissioned) and suspended accounts are denied.
        // ------------------------------------------------------------------
        if (! $user->status->canAuthenticate()) {
            Auth::logout();
            RateLimiter::hit($this->throttleKey());

            Log::warning("Login failed: account status is '{$user->status->value}'.", [
                'user_id' => $user->id,
                'status'  => $user->status->value,
                'ip'      => $this->ip(),
            ]);

            throw ValidationException::withMessages([
                'email' => trans('auth.failed'),
            ]);
        }

        // ------------------------------------------------------------------
        // Step 4-5: Verify at least one active role is assigned.
        // Roles with status 'draft' or 'deprecated' do not grant access.
        // Users with no roles, or only non-active roles, are denied.
        // ------------------------------------------------------------------
        $hasActiveRole = $user->roles()
            ->where('status', RoleStatus::Active->value)
            ->exists();

        if (! $hasActiveRole) {
            Auth::logout();
            RateLimiter::hit($this->throttleKey());

            Log::warning('Login failed: no active role assigned.', [
                'user_id' => $user->id,
                'ip'      => $this->ip(),
            ]);

            throw ValidationException::withMessages([
                'email' => trans('auth.failed'),
            ]);
        }

        // ------------------------------------------------------------------
        // Step 6: All checks passed — clear rate limiter and log success.
        // Session ID is regenerated by the controller after this method returns.
        // ------------------------------------------------------------------
        RateLimiter::clear($this->throttleKey());

        Log::info('Login successful.', [
            'user_id' => $user->id,
            'email'   => $user->email,
            'ip'      => $this->ip(),
        ]);
    }

    /**
     * Ensure the login request is not rate limited.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function ensureIsNotRateLimited(): void
    {
        if (! RateLimiter::tooManyAttempts($this->throttleKey(), 5)) {
            return;
        }

        event(new Lockout($this));

        $seconds = RateLimiter::availableIn($this->throttleKey());

        throw ValidationException::withMessages([
            'email' => trans('auth.throttle', [
                'seconds' => $seconds,
                'minutes' => ceil($seconds / 60),
            ]),
        ]);
    }

    /**
     * Get the rate limiting throttle key for the request.
     */
    public function throttleKey(): string
    {
        return Str::transliterate(Str::lower($this->string('email')) . '|' . $this->ip());
    }
}

